### PR TITLE
Add `rui` and `icons` module

### PR DESCRIPTION
**Pull request by Conner1115**
Added the `rui` and `icons` module, which can be imported from `@replit/extensions/rui` and `@replit/extensions/icons`.

**Changed files** (excluding imported components):
 - `package.json`
     - Added the modules and their type declarations
 - `src/rui/components/Rui.tsx`
     - A wrapper component that injects the CSS vars of the user's theme
     - Falls back to the default replitDark theme if not an extension/failed to fetch theme
 - `src/react/useThemeValues`
     - Fixed an accidental incorrect name.  The hook name was supposed to be `useThemeValues` but was `useTheme` instead
 - `src/themes/global`
     - Added some `interactive` tokens at the end since those were causing some tokens with elevation to go whacky
 - `example/App.tsx`
     - Changed up the example yet again to use RUI and an icon to make sure it works

**Example Usage**

```tsx
import { Rui, View, Text } from '@replit/extensions/rui';
import { Puzzle } from '@replit/extensions/icons';

function App() {
  return (
    <View>
      <Text variant="headerBig">Extension <Puzzle size={32} /></Text>
    </View>
  );
}
```

### CODE REVIEW

**Comment by Conner1115** [comment]
Note to self: add docstrings and example usage for every RUI component

**Comment by lafkpages** [comment]
Why did this get closed? 🤔

**Comment by Conner1115** [comment]
too many stuff in one single package, will attempt to do this again in the future

**Comment by Bookie0** [comment]
hai

**Comment by pikachub2005** [comment]
> hai

lol

**Comment by sk337** [comment]
are well all commenting on this

**Comment by Bookie0** [comment]
no

**Comment by pikachub2005** [comment]
yes

**Pull request closed without merging**
