### PR TITLE
Execution API

### PR DESCRIPTION
**Pull request by Conner1115**
Waiting on https://github.com/replit/repl-it-web/pull/31698 to be merged first

### CODE REVIEW

**Comment by lafkpages** [comment]
Yo finally! Thanks!

**Comment by lafkpages** [comment]
Wait, why is it in FS? `replit.fs.exec()`?

**Comment by Conner1115** [comment]
Closing for now, the exec api is not anything like how this PR is at the moment.

**Comment by lafkpages** [comment]
nooooo

**Pull request closed without merging**
